### PR TITLE
Add camera support

### PR DESCRIPTION
**Pull request by ghost**
This also requires https://github.com/android-rpi/kernel_arpi/pull/2. Hotplug is not supported.

### CODE REVIEW

**Comment by ghost** [comment]
It does build, but I can't test it, because I don't have the RPi camera

**Comment by ramasamyesvar** [comment]
Does this work for both Raspberry pi camera and usb webcam ?

**Comment by ghost** [comment]
No, but I'll also add that.

**Comment by ghost** [comment]
I tried adding it, please test it if you want.

**Comment by ramasamyesvar** [comment]
Without the external camera change I tries and it says camera not available. 
2020-06-21 23:22:06.393 1165-1165/com.simplemobiletools.camera W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@f82e7c8
2020-06-21 23:22:06.456 1165-1165/com.simplemobiletools.camera W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@1c9c1e3
2020-06-21 23:22:06.562 1165-1165/com.simplemobiletools.camera W/CameraBase: An error occurred while connecting to camera 0: Status(-8, EX_SERVICE_SPECIFIC): '4: connectHelper:1418: No camera device with ID "" currently available'
2020-06-21 23:22:06.589 1165-1165/com.simplemobiletools.camera W/OrientationEventListener: Cannot detect sensors. Not enabled


I  will try the external camera changes now

**Comment by ghost** [comment]
Do they work?

**Comment by ramasamyesvar** [comment]
I thought I could use my Nikon camera as USB but couldn't. I have ordered a webcam.  I Will test after I receive it. With raspberry pi camera is gives that error.

Does it need more entries for camera sepolicy. I get the AVC denied errors. 
Like this https://android.googlesource.com/device/google/marlin/+/android-o-preview-2/sepolicy/camera.te

**Comment by ghost** [comment]
Can you please do this:
- Connect a camera (either USB or RPi)
- Run logcat
- Open the camera app
- Send me the logcat output
- Run `find /dev` with adb shell
- Send me the output

I also updated the kernel PR for USB support, make sure you got the changes there too.

**Comment by ramasamyesvar** [comment]
Please find the logs. find /dev in the begining
[camera.txt](https://github.com/android-rpi/device_arpi_rpi4/files/4826944/camera.txt)
 Yes it has all kernel changes including USB
This is the branch I use https://github.com/ramasamyesvar/device_arpi_rpi4/tree/rpi4_arpi10

**Comment by ghost** [comment]
Thank you! What camera was connected while running `find /dev`? Please test USB and RPi. (note: For RPi, the camera has to be plugged in before turning the Pi on, reboot between testing USB and RPi cam).

**Comment by ramasamyesvar** [comment]
Internal Camera. Didn't get USB cam yet.  The /dev/video0 is not found. If I use a different build like the lineage I could see the video. Pasting the working logs from a different build just FYR

[camworking.txt](https://github.com/android-rpi/device_arpi_rpi4/files/4836178/camworking.txt)

**Comment by ramasamyesvar** [comment]
Any reason why you closed this issue

**Pull request closed without merging**
