### PR TITLE
USB Support over USB-C on RPI4

### PR DESCRIPTION
**Pull request by Flemmard**
Initial support of USB (adb, etc) for RPi4b.
init.usb.rpi4.rc might need some work, but it seems to work as it is.

### CODE REVIEW

**Comment by Flemmard** [comment]
This needs https://github.com/android-rpi/kernel_arpi/pull/1

**Comment by peyo-hd** [comment]
Merged with small modification.

**Comment by peyo-hd** [comment]
Made USB client-mode optional with https://github.com/android-rpi/device_arpi_rpi4/commit/ad376c69328339c381b9d51680f4431faf9b70b6.
Since powering rpi4 through Host USB port caused Host stability issues.

**Comment by Flemmard** [comment]
I'll try to find a way to enable or disable at in a different way.
I'm not sure we can have adb on other ports ?

**Comment by peyo-hd** [comment]
ADB can be used via ethernet.  " adb connect <IP Addr>" from host.

**Comment by Flemmard** [comment]
Yeah right, I used a Arduino to make an UART adapter it's another way too but adb is a bit faster :D 

Right now I'm working on a way to package everything into a flashable IMG via the raspberry tool

**Pull request closed without merging**
