### PR TITLE
Switch to ARM64

### PR DESCRIPTION
**Pull request by ghost**
This PR enables arm64 support. I don't know if you want to have that, but I think it would be better, since it allows more apps, like dolphin.

### CODE REVIEW

**Comment by peyo-hd** [comment]
I have considered 64bit build, but decided to keep 32bit build for a while.
You can proceed on forked project.

**Comment by ghost** [comment]
Ok, sure.

**Comment by dimitry-ishenko** [comment]
@RaspberryPiFan I see you have projects on both gitlab and github. I am trying to get 64-bit builds working on rpi3 and rpi4. What's the best way to contact you? (I promise not to bug too much :smile:)

**Comment by ghost** [comment]
@peyo-hd https://www.raspberrypi.org/blog/8gb-raspberry-pi-4-on-sale-now-at-75/ needs ARM64

**Comment by ghost** [comment]
@dimitry-ishenko You can contact me here: https://discord.gg/t5HjtRR

**Pull request closed without merging**
